In [22]:
import pandas as pd
df=pd.read_csv("C:\\Users\\Smita Akolkar\\Downloads\\salaries.csv")
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [23]:
inputs=df.drop("salary_more_then_100k",axis="columns")
target=df["salary_more_then_100k"]
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [24]:
from sklearn.preprocessing import LabelEncoder

In [25]:
le_company=LabelEncoder()
le_job=LabelEncoder()
le_degree=LabelEncoder()

In [26]:
inputs["company_n"]= le_company.fit_transform(inputs["company"])
inputs["job_n"]= le_job.fit_transform(inputs["job"])
inputs["degree_n"]= le_degree.fit_transform(inputs["degree"])
inputs.head()

  company                  job     degree  company_n  job_n  degree_n
0  google      sales executive  bachelors          2      2         0
1  google      sales executive    masters          2      2         1
2  google     business manager  bachelors          2      0         0
3  google     business manager    masters          2      0         1
4  google  computer programmer  bachelors          2      1         0

In [27]:
inputs_n=inputs.drop(["company","job","degree"],axis="columns")
inputs_n

    company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [28]:
from sklearn import tree

In [29]:
model=tree.DecisionTreeClassifier()

In [30]:
model.fit(inputs_n,target)

DecisionTreeClassifier()

In [31]:
model.score(inputs_n,target)

1.0

In [32]:
model.predict([[2,2,1]])

C:\Users\Smita Akolkar\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0], dtype=int64)

In [33]:
##Titanic

In [34]:
import pandas as pd
from sklearn import tree

In [42]:
df=pd.read_csv("C:\\Users\\Smita Akolkar\\Downloads\\titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [44]:
df["Age"]=df["Age"].fillna(inputs.Age.mean())
df.head()
df.isnull().sum()
df.columns

AttributeError: 'DataFrame' object has no attribute 'Age'

In [37]:
target=df.Survived
target.head()
df.drop(["PassengerId","Name","Ticket","Cabin","Embarked"],axis="columns",inplace=True)

In [38]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0         0       3    male  22.0      1      0   7.2500
1         1       1  female  38.0      1      0  71.2833
2         1       3  female  26.0      0      0   7.9250
3         1       1  female  35.0      1      0  53.1000
4         0       3    male  35.0      0      0   8.0500

In [39]:
target=df["Survived"]
target.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [40]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
dtype: int64

In [41]:
df.Age=df["Age"].fillna(inputs.Age.mean())
df.head()
df.isnull().sum()

AttributeError: 'DataFrame' object has no attribute 'Age'

In [21]:
input_n=df.drop("Survived",axis="columns",inplace=True)

AttributeError: 'DataFrame' object has no attribute 'Survived'

In [70]:
from sklearn.preprocessing import LabelEncoder

In [71]:
le_sex=LabelEncoder()

In [76]:
input_n["Sex"]=le_sex.fit_transform(input_n["Sex"])
input_n.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S
4,5,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,S

In [73]:
model=tree.DecisionTreeClassifier()

In [74]:
model.fit(inputs,target)

ValueError: could not convert string to float: 'Braund, Mr. Owen Harris'